### PR TITLE
display borrower details

### PR DESCRIPTION
**Pull request by Kirosoft**

### CODE REVIEW

**Comment by Phemus** [comment]
:+1: Looks good to merge though do not merge without US5 on the deep API being merged first

**Comment by danielmarker** [comment]
I may be out of touch here with Jinja 2 - but syntax seems back to front:

<li><a>{{ borrower.forename}}{% if borrower.middle_name %} {{ borrower.middle_name}} {% endif %}{{
-            borrower.surname}}</a></li>

Surely the above should be used to ensure middle name is only printed if present - current work will just print " " or None I would have thought?

**Comment by danielmarker** [comment]
Or even: {{ '[%s]' % borrower.middle_name if borrower.middle_name }}

**Comment by Phemus** [comment]
@danielmarker i made the same mistake the if statement is to add a blank space if there is a middle name not the middle name itself

**Comment by danielmarker** [comment]
Agree on that but does Postgres pass back a None object rather than a blank string

**Comment by endamccormack** [comment]
:+1:

**Pull request merged**
